### ISSUE TITLE
Telekinetic doesn't provide power

### ISSUE THREAD

**Issue by Aquifn** [SolastaMods/SolastaUnfinishedBusiness#2449] opened 2023-02-13 23:14 UTC
For a while now, Telekinetic hasn't given the power to push. Just doesn't show up anywhere on the UI during combat. I loved the combination on my armorer inventor, a great way to use bonus actions. Now, however, it's a wasted feat slot. I've started a few different armorers over the past week, and it doesn't show up on any of them.

**Comment by ThyWoof** [comment] 2023-02-14 04:32
Please share a save. Each game and heroes are unique.

**Comment by Aquifn** [comment] 2023-02-14 07:22
https://www.dropbox.com/s/tlbpisg2bg9wr56/threesome.sav?dl=0

**Comment by ThyWoof** [comment] 2023-02-14 16:50
your save indeed doesn't show the action. sometimes when we fix bugs powers acquired on an earlier stage might not fully work as intended. fully read the changelog for changes on features you use. if you face issues like above, RESPEC.

cannot reproduce on a brand new inventor:
![image](https://user-images.githubusercontent.com/13087646/218803212-594ba187-25d7-4337-b332-d41e0b6b05d9.png)


closing.

**Closed by ThyWoof** 2023-02-14 16:50 UTC
