### ISSUE TITLE
Quick Wit procs on EVERYTHING

### ISSUE THREAD

**Issue by Pikachar2** [SolastaMods/SolastaUnfinishedBusiness#4320] opened 2024-02-02 05:04 UTC
[Palace_Office_7.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/14135159/Palace_Office_7.zip)

Quick Wit prompt pop up shows up on everything but attacks.
This is both on friendly and enemy actions.
Sometimes it shows up multiple times per action.

Things we've encountered so far:
- Sorcerer casting fly on the Paladin
- Sorcerer creating sorcery points.
- Anyone casting shield
- Artificer casting Booming Smite (not the activation, but the casting of smite)
- Channel Divinity
- Artificer casting Blade Barrier

**Comment by ThyWoof** [comment] 2024-02-02 15:05
I cannot reproduce this in  SP. Can you share specific steps to get to the issue?

**Comment by ThyWoof** [comment] 2024-02-02 20:54
Was able to repro and fixed in my local box

**Closed by ThyWoof** 2024-02-02 20:54 UTC
