### ISSUE TITLE
Web Saves Should be Strength but are Dex

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#3245] opened 2023-05-19 17:42 UTC
Title - Campaign is Morrow's Deep. Look at combat log or pass a few turns to recreate (might require save scumming).
Reusing this save for tickets #3246 & #3247 

Side note: Aren't spiders supposed to be immune to Web?

[Summon Skellington & Web Dex.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11519207/Summon.Skellington.Web.Dex.zip)

**Comment by ThyWoof** [comment] 2023-05-19 18:11
Share a screenshot. Code clearly uses STR checks.

**Comment by MartinBrandstrup** [comment] 2023-05-19 20:03
As far as I can tell:
Minotaur is restrained -> Minotaur rolls Dex --> Minotaur restrained is refreshed

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/44898614/50dc35fd-493a-409d-8b8b-2570b8005437)

**Comment by ThyWoof** [comment] 2023-05-19 20:51
Web does a DEX saving at the begging of the turn per rules. On top of that an enemy needs to do a strength ability check. It’s working as expected except for I should add an exception to all spiders in game to have a condition immunity against web. Closing as not a bug.

**Closed by ThyWoof** 2023-05-19 20:51 UTC

**Comment by ThyWoof** [comment] 2023-05-19 22:02
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/b7a4dd42-32f7-4a48-90f0-2b5e2cf6eeac)
