### ISSUE TITLE
Eldritch smite pops up only when a critical hit

### ISSUE THREAD

**Issue by HIEROT** [SolastaMods/SolastaUnfinishedBusiness#3145] opened 2023-05-06 16:37 UTC
It should behave like a paladin's smite, and possibly it will be very nice if a button to on/off critical smite is provided just like a paladin
[AutoSave_2.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11412810/AutoSave_2.sav.zip)
Thank you in advance!

**Comment by HIEROT** [comment] 2023-05-06 16:39
And I remember in the last few versions of mod, it behaves as it should be. Maybe something was modified unexpectedly

**Comment by ThyWoof** [comment] 2023-05-06 16:46
In fact there is an option for that. Are you sure you don't have Enable Paladin Smite Toggle enabled and forgot to enable the toggle?


this is the logic there.

```
                        // This is used to only offer smites on critical hits
                        if (!criticalHit &&
                            Main.Settings.AddPaladinSmiteToggle &&
                            !hero.IsToggleEnabled((ActionDefinitions.Id)ExtraActionId.PaladinSmiteToggle))
                        {
                            break;
                        }
```

here without setting enabled on Mod UI.
![image](https://user-images.githubusercontent.com/13087646/236636612-c417fee1-44b3-49b9-99d2-906078923365.png)

toggle disabled. no smites offered.
![image](https://user-images.githubusercontent.com/13087646/236636695-3cbb9f3d-d53a-4511-9ff2-dded4aea5015.png)

not a bug.

**Comment by HIEROT** [comment] 2023-05-06 20:20
I mean the toggle of invocation eldritch smite of a warlock. I was sure that the toggle for a paladin is there but not for a warlock.
![image](https://user-images.githubusercontent.com/55292746/236645090-d11f9daa-e182-4d9d-bfd1-beaa060b795d.png)

**Comment by ThyWoof** [comment] 2023-05-06 23:24
Oh I see. Will check

**Comment by ThyWoof** [comment] 2023-05-06 23:42
fixed in dev.

added an additional check to let this smite type go without the toggle. For now won't add any toggle.

```
                        // This is used to only offer smites on critical hits
                        if (!criticalHit &&
                            // allows EldritchSmite to pass through
                            featureDefinition is not FeatureDefinitionAdditionalDamage &&
                            // allows PaladinSmite to pass through
                            Main.Settings.AddPaladinSmiteToggle &&
                            !hero.IsToggleEnabled((ActionDefinitions.Id)ExtraActionId.PaladinSmiteToggle))
                        {
                            break;
                        }
```

**Closed by ThyWoof** 2023-05-06 23:42 UTC

**Comment by HIEROT** [comment] 2023-05-26 10:35
`if (!criticalHit &&
                            Main.Settings.AddPaladinSmiteToggle &&
                            featureDefinition is not FeatureDefinitionAdditionalDamage &&
                            !hero.IsToggleEnabled((ActionDefinitions.Id)ExtraActionId.PaladinSmiteToggle))
                        {
                            break;
                        }`
I noticed that the **not** is missing in the newest dev. Adding it fixs the issue.
