### ISSUE TITLE
.85 patch changes armor proficiencies...

### ISSUE THREAD

**Issue by Aremihc** [SolastaMods/SolastaUnfinishedBusiness#3179] opened 2023-05-10 03:10 UTC
Fighter does not have Heavy Armor in .85 (DOES in .84), Forceblade does not have shields, etc.

**Comment by ThyWoof** [comment] 2023-05-10 03:45
cannot reproduce creating new heroes:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/34584454-45ff-4c77-a108-71d23ceaba01)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/4ae8a793-0202-4a33-bd6c-d2e71e1ed2dc)

also cannot reproduce on existing saves.

forceblade don't get shield:
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/c3dba127-585f-4d17-b548-930d51f0b1a3)

not a bug. only possible issue with fighter is if you wrongly removed heavy armor proficiency using the party editor which is beta and unsupported.

closing.

**Closed by ThyWoof** 2023-05-10 03:45 UTC

**Comment by Aremihc** [comment] 2023-05-11 01:49
Weird... It's fine now. It was every Heavy Armor class, even existing ones... Strange. Thanks for the quick bug check.
