### ISSUE TITLE
6 man party

### ISSUE THREAD

**Issue by Ulgroth** [SolastaMods/SolastaUnfinishedBusiness#2759] opened 2023-03-17 19:59 UTC
1.4.33.60 - only other mods i have are user campaigns and nothing else

Someone made a 6 man party map and when I override the party size the Ui doesnt expand and ive clicked the button after u make the party bigger to "allow all players on narrative sequence". Ive tried looking for a slider bar, changing the window resolutions and also restarting the game everytime i made a change. Chances are im just missing something blatantly obvious but if you could provide any help that would be great.

Link to modder of the 6 man campaign if that matters
https://steamcommunity.com/sharedfiles/filedetails/?id=2942835978

To repoduce the bug i just hit new adventure after adjusting the systems in your mod. I will attach a picture as reference though.

![20230317145302_1](https://user-images.githubusercontent.com/128185423/226018278-2b85f405-8844-40be-a012-7dfdc73cd87f.jpg)

![20230317145919_1](https://user-images.githubusercontent.com/128185423/226019206-c97b1636-87a1-475c-88fc-1a22a3c83a0e.jpg)

**Comment by ThyWoof** [comment] 2023-03-17 20:04
This simply works. Ensure you start a new campaign after you make the change on mod UI.

**Comment by Ulgroth** [comment] 2023-03-17 20:20
@ThyWoof  Sir i have provided 2 pictures showing that i clicked new adventure as well as showing that ive clicked the additional button to expand the ui. So telling me to start a new campaign after making the changes to the UI is not making sense to me. Is new adventure not a new campaign? Is there another button for expanding the Ui that im missing? I cant even actually start the new campaign unless im able to select 6 characters, which i cant as stated.

**Comment by ThyWoof** [comment] 2023-03-17 20:23
It's something we haven't touched in months. Change mod UI to 6 players, start a new adventure. That's it. If you change MOD UI with the NEW ADVENTURE screen open you won't see the changes.

![image](https://user-images.githubusercontent.com/13087646/226029578-75d111bc-6a6b-406f-a2f1-ee5dda6c5ef5.png)

Closing this as not a bug.

**Closed by ThyWoof** 2023-03-17 20:23 UTC

**Comment by Ulgroth** [comment] 2023-03-17 20:27
@ThyWoof I have tried that already. I have restarted in between each save as most of the time when i make changes it usually requires a restart to work. The reason i showed those pictures while in the adventure mode was to show u that i had the settings set and a picture of the UI within one picture instead of taking double the pictures.
