### ISSUE TITLE
Eldritch Surge Warlock has permanent bonuses from Eldritch Versatility

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#5038] opened 2024-11-07 04:38 UTC
Save game and two screen shots attached. Basically, no "versatility switch" appears on toolbar and when I go to the party editor, it shows that the Warlock's STR, INT, and WIS are at a constant +2 bonus from "Eldritch Versatility". 

I've used this class before and there was a switch to either get the benefit of ONE of these +2 stats or use the eldritch surge invocations, that appears to have disappeared? Anyway, this Warlock is crazy overpowered with constant +2's to STR, INT, and WIS.

Thanks.
[Archive.zip](https://github.com/user-attachments/files/17656066/Archive.zip)

**Comment by Bawookles** [comment] 2024-11-07 10:20
Sorry. I was looking at it wrong.

**Comment by Bawookles** [comment] 2024-11-07 10:28
Looking at it further, the "Versatility Switch" is there but it does nothing, the STR, INT, and WIS +2 bonuses are always "on" even if one switches to the invocations. Thanks.

**Comment by HIEROT** [comment] 2024-11-13 12:20
hello I am the creator and coder of this subclass, but I tested it and find no problem on my side. Maybe the stat is permanently added due to some untracked status. I think respec the character will solve this problem, thanks)

**Comment by HIEROT** [comment] 2024-11-14 16:59
Oh I get what you mean. Yes, this feature indeed grants permanent bonus to Str, Int and Wis equal to the amount of learnt versatilities. But this is based on following observations:
1. This sub requires pure build to shine, and any dip will cause great loss of power. So the benefit of multiple bonus to attributes are limited as the sub has no other means to utilize these attributes.
2. If any other class dips a level of this sub, yep, it gets +2 to three attributes, but it loses 1 level of progression and there is no other benefit cause Blast Exclusive will force EB beam number to 1 regardless of total levels so you can't benifit from EB as a dip. So its power is controlled.

**Comment by ThyWoof** [comment] 2024-11-16 17:09
Up to you Hierot if you wanna tweak descs or sub. Closing this as not a bug.

**Closed by ThyWoof** 2024-11-16 17:09 UTC

**Comment by HIEROT** [comment] 2024-11-16 21:24
_The Eldritch Surge Warlock is already a total DPR machine gun, it doesn't need any more help!_

This is true maybe for the last version of this sub lol (2 EBs per turn), but after last tweak it can only fire once. So max Dpr at lvl 20 is like 5 * (d10 + 3d8 + cha + str) = 145 now, plus requiring long rest resource (chain pseudo dragon), spell concentration (spirit shroud) and close proximity. I think the curve is smooth and moderate). Its role is more like a protector and powerful spellcaster with wis and int versatilities, EB and str versatilities are just dmg complement and means to earn points.  Feel free if you have other questions ԅ(¯ㅂ¯ԅ) have fun
