### ISSUE TITLE
Skin of Retribution Damage Doesn't Scale with Spell Level

### ISSUE THREAD

**Issue by Pikachar2** [SolastaMods/SolastaUnfinishedBusiness#3944] opened 2023-08-28 23:51 UTC
As the title says, the Skin of Retribution spell is not scaling its damage upon upcasting it.
Actual: Skin of Retribution damage is 5.
Expected: Skin of Retribution damage should be 5*spell level.

The save included has a 3rd lvl Sorcerer with Skin of Retribution on its turn. This gives options to cast it at either lvl 1 or 2. And then walk to the goblin and walk away to see what damage it takes.
[test2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12458908/test2.zip)

@Pikachar in the UB discord channel if you need more info from me.

**Comment by raptorixx** [comment] 2023-08-29 23:35
I can confirm this too! I noticed this when I saw the temp hp being correctly applied but not the damage since it still remained 5 damage.

**Comment by ThyWoof** [comment] 2023-09-01 20:14
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/dc9bc9ca-72da-4ce1-888e-d2df35d8da82)
fixed in DEV.

**Closed by ThyWoof** 2023-09-01 20:14 UTC
