### ISSUE TITLE
Mod instability warning when you select wyrmkin in race menu

### ISSUE THREAD

**Issue by UWImban** [SolastaMods/SolastaUnfinishedBusiness#3686] opened 2023-07-02 05:25 UTC
Immediately after you select the new Wyrmkin race in the race menu during character creation, you get a mod instability warning popup. It didn't seem to have any immediate effects, but I didn't try going through the rest of character creation to be sure.

I reinstalled UB to make sure this was still happening on a fresh installation.

**Comment by sheva75** [comment] 2023-07-02 09:06
I notice, when Making Cave Wyrmkin Race, after awhile you cant move, i made an monk not sure if that class make any issues?

**Comment by otearaisu** [comment] 2023-07-02 10:36
@UWImban Seems this is related to the language name. Will fix.

@sheva75 What subclass are you using and how do you replicate it?

**Comment by otearaisu** [comment] 2023-07-02 10:47
@UWImban Can I have Player.log when you encountered the error? Seems I can no longer replicate it.

**Comment by UWImban** [comment] 2023-07-02 10:58
I believe this should be it. [Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11929287/Player.log)

**Comment by otearaisu** [comment] 2023-07-02 11:50
@UWImban Can you check these two options when playing Cave Wyrmkin?
![checkoptions](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135924218/a6c987a8-cb00-4622-912a-d09566098d31)

**Comment by sheva75** [comment] 2023-07-02 11:59
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/52861010/969d7675-f5d0-484d-9907-983e9895e7aa)

This one, i will try to do this that aswell

**Comment by sheva75** [comment] 2023-07-02 12:05
where is the player.log ?

**Comment by sheva75** [comment] 2023-07-02 12:09
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11929460/Player.log)

I guess here

**Comment by sheva75** [comment] 2023-07-02 12:13
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/52861010/aa1a94d2-7cca-4591-a10d-51dc68e3c122)

I get a warning right away when pressing that Cave Wyrmkin icon

**Comment by otearaisu** [comment] 2023-07-02 12:21
@sheva75 Did you uncheck it instead of checking? 😅

**Comment by otearaisu** [comment] 2023-07-02 12:22
> @otearaisu
> 
> ![image](https://user-images.githubusercontent.com/52861010/250354406-969d7675-f5d0-484d-9907-983e9895e7aa.png)
> 
> This one, i will try to do this that aswell

For this, can you log a new issue? Seems unrelated to the original one.

**Comment by sheva75** [comment] 2023-07-02 12:26
Also i wonder why the feat selection at level 2 why there is no monk weapon specialization for Unarmed Fighting?

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/52861010/b7376256-aa7b-41fc-aa36-7dcd2b7eba98)

**Comment by sheva75** [comment] 2023-07-02 12:57
> @sheva75 Did you uncheck it instead of checking? 😅

@otearaisu 

im checking now i think its need a restart

**Comment by sheva75** [comment] 2023-07-02 13:02
> > @sheva75 Did you uncheck it instead of checking? 😅
> 
> @otearaisu
> 
> im checking now i think its need a restart

nothing works unchecked or check

**Comment by sheva75** [comment] 2023-07-02 13:22
> > @otearaisu
> > ![image](https://user-images.githubusercontent.com/52861010/250354406-969d7675-f5d0-484d-9907-983e9895e7aa.png)
> > This one, i will try to do this that aswell
> 
> For this, can you log a new issue? Seems unrelated to the original one.

The issue is that you get an mod warning and not able to move with zero movement points? Or at least that what i experience i did a new character several times same problem

**Comment by otearaisu** [comment] 2023-07-02 13:33
@sheva75 Can you give me a save file? I have difficulties replicating the issue.

**Comment by sheva75** [comment] 2023-07-02 13:41
> @sheva75 Can you give me a save file? I have difficulties replicating the issue.

sure i will give a save file, need to do an zip file as this dont support rar files

**Comment by sheva75** [comment] 2023-07-02 13:43
> @sheva75 Can you give me a save file? I have difficulties replicating the issue.

[olle2back.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11929670/olle2back.zip)

@otearaisu here is the save

**Comment by otearaisu** [comment] 2023-07-02 13:57
@sheva75 When did this happen? Have you tried playing it when it is still working? Seems all race features are missing. Have you tried respec the character?

**Comment by otearaisu** [comment] 2023-07-02 13:59
Original:
![20230702215258_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135924218/77c33e3c-31f4-48da-8f7b-d648fe49aa91)
Respecced:
![20230702215555_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135924218/b3bb96a6-cc32-4bff-b5f2-279b0ac2e807)

**Comment by sheva75** [comment] 2023-07-02 14:22
> Original: ![20230702215258_1](https://user-images.githubusercontent.com/135924218/250361669-77c33e3c-31f4-48da-8f7b-d648fe49aa91.jpg) Respecced: ![20230702215555_1](https://user-images.githubusercontent.com/135924218/250361667-b3bb96a6-cc32-4bff-b5f2-279b0ac2e807.jpg)

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/52861010/24bd7421-da22-4279-912a-9cbb162a107a)

I just respec and still dont have Ancestry Features, but i cant see in the picture if you have move more then 0?

**Comment by sheva75** [comment] 2023-07-02 14:23
If you have then it is something in Unfinished Business Settings that need to get back to original state

**Comment by otearaisu** [comment] 2023-07-02 14:38
Can you follow these steps:
- Check "Unlock skin colors" in UB screen
- Restart Solasta
- Respec the Cave Wyrmkin. It should not show the "Mod warning"
- Check the skin color options, should have many:
![20230702223716_1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/135924218/bff67736-d2d8-4899-a1c9-854ba6a2a9a2)

**Comment by sheva75** [comment] 2023-07-02 14:46
Im trying different mods and adventures now, 4 man and 6 man. Still same problem, Im making 2 new monks now, new adventure, bot of them have 0 move.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/52861010/5fad96d9-6c55-418a-a01b-d213f1514b2d)

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/52861010/c5aee5c2-9c1b-4a77-9a18-6a1746728e38)

**Comment by sheva75** [comment] 2023-07-02 14:47
Okay i will try that now

**Comment by sheva75** [comment] 2023-07-02 14:57
> 

It Seems to work

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/52861010/1f8337f2-0a22-4060-80d2-f5e643c0190b)

**Comment by ThyWoof** [comment] 2023-07-02 15:27
Fixed in dev.

**Closed by ThyWoof** 2023-07-02 15:27 UTC
