### ISSUE TITLE
Shield Expert feat not granting shield proficiency

### ISSUE THREAD

**Issue by gobsmacked1** [SolastaMods/SolastaUnfinishedBusiness#3110] opened 2023-05-02 03:53 UTC
Just noticed this one when leveling up a wizard.  Could've sworn this used to grant the proficiency itself in previous versions.  My wizard took the Sellsword background for medium armor proficiency (which doesn't grant shield prof).  Later took Warcaster in planning to eventually take Shield Expert.  Technically the RAW Shield Expert feat REQUIRES shield proficiency before it can even be taken, which I just saw on a few different 5e sites.  So either way you look at it, this one is a little bugged for the verbiage.  Will have to respec since it's an unusable feat.

https://www.5esrd.com/database/feats/shield-expertise/

![ShieldExpert_Feat](https://user-images.githubusercontent.com/101536157/235574483-1e19447f-785e-45ef-90bd-7d7d0cbc589e.png)
![ShieldExpert_NotGrantingProficiency](https://user-images.githubusercontent.com/101536157/235574490-9f48d2bc-2c8b-4276-a01b-6c04d6786d5a.png)

**Comment by gobsmacked1** [comment] 2023-05-03 01:39
The plot thickens.  So I confused/misremembered, "Shield Expert" with the, "Raise Shield" feat, which _does_ grant shield proficiency.  HOWEVER, because I took Sellsword for my background I should've already been granted shield proficiency at level 1 by virtue of being given the medium armor proficiency feat.  So if the background is granting the medium armor feat, and that feat is written up accurately, Sellsword is broken (?).

![MediumArmorFeat](https://user-images.githubusercontent.com/101536157/235818362-1cd9967b-03b5-45ae-b331-5e849fb096e3.png)
![SellswordBackground](https://user-images.githubusercontent.com/101536157/235818367-339f35b0-eafb-4561-b70f-d40ad06cfc1d.png)

**Comment by ThyWoof** [comment] 2023-05-03 02:05
I cannot comment on that background. Shield and Medium armor proficiency are different in game. TA might have their reasons for doing that.

Closing as not a bug.

**Closed by ThyWoof** 2023-05-03 02:05 UTC
