### ISSUE TITLE
1.4.33.64 corrupt characters, can't update beyond

### ISSUE THREAD

**Issue by gobsmacked1** [SolastaMods/SolastaUnfinishedBusiness#2902] opened 2023-04-03 02:10 UTC
My kid and I are half-way through the campaign, and all updates newer than 1.4.33.65 break all prior saved games.  

The error won't tell me _which_ character is corrupt, and won't load any of our previous games...of the entire campaign.  

I even tried rolling back to 1.4.33.64, reloading the last saved game, and then respec'ing our characters back to Level 1, in the hopes that that respec'd saved game would actually load under 1.4.33.67.  NO SUCH LUCK.

Glad to see Dev is still going strong.  But again, it hurts the community you're trying to help when you brick an entire campaign's worth of progress and ask us to start over in order to take any further updates.

Until/if this gets fixed we're stranded on 1.4.33.64.

[Stuck.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11134115/Stuck.zip)
![MiddleOfCampaign](https://user-images.githubusercontent.com/101536157/229395869-4cf2316c-b4a9-4967-b86f-a5795625ff4b.jpg)

**Comment by MartinBrandstrup** [comment] 2023-04-03 06:48
So I had a similar challenge yesterday trying to roll back and do all sort of shenanigans.
Turns out that the game had not automatically updated to .67 on first launch (and it was .66 that was broken) which means that rolling back and then updating fixed the correct version.

What I learned from this debacle and what I am almost certain is your problem as well is that **when you roll back all your mod settings gets reset**, which will for sure make the character appear corrupted. You need to reproduce the exact settings you had before the rollback and then it should work again :)

**Comment by ThyWoof** [comment] 2023-04-03 19:43
Anything else you could remember? The only BP we changed that could had caused this was crusher. Would you be able to export the all the heroes from the working save / mod version and share here?

**Comment by gobsmacked1** [comment] 2023-04-04 00:46
I have a working .64 Monk with the Crusher feat, taken at level 1.  Everything went to pot after .65.  I attached the .64 save zip up in the original post (Stuck.zip).  I don't know how to export characters individually.  So all you'd need to do--if you want to check them out firsthand, is revert your mod install to .64 and load that saved game.

I can try to respec the monk again, only this time not take Crusher if that's the only incompatibility stopping me from taking .67.

**Comment by gobsmacked1** [comment] 2023-04-04 03:34
Must've been the Monk's Crusher.  After respec'ing and picking another feat at Level 1, I was able to take further updates from the .64 save.  Should be noted that the new .67 Crusher toggle doesn't indicate whether it's ON or OFF.

**Comment by ThyWoof** [comment] 2023-04-04 03:37
Thanks for the heads up on crusher. That got already fixed on dev.

**Closed by ThyWoof** 2023-04-04 03:37 UTC
