### ISSUE TITLE
Chain lightning mode setting problem

### ISSUE THREAD

**Issue by kdgmo** [SolastaMods/SolastaUnfinishedBusiness#4600] opened 2024-05-11 02:43 UTC
In the case of Chain Lightning, if all targets are specified through the mode settings, the bonus effect of Blue Dragon Bloodline will not be applied to all targets except the first target.
If you do not set the mode, all targets will see the effect.
https://drive.google.com/file/d/1zb0T9Fi-xqjwBMECT7olgcDnuvxgtGNE/view?usp=drive_link

**Comment by ThyWoof** [comment] 2024-05-11 03:52
this setting was written a long time ago, back in 2021. if I remember the main reason behind it is because chain lightning can target enemies that cannot be perceived. I believe a better solution is to simply fix that which I just tested with a very simple patch.

big chances will end up removing this setting all together.

@PhilPJL , I believe you wrote this one, correct?

**Comment by ThyWoof** [comment] 2024-05-11 03:52
`    //BUGFIX: Chain Lightning allow targeting enemies that cannot be perceived creating soft lock situations
    [HarmonyPatch(typeof(GameLocationTargetingManager), "IGameLocationTargetingService.ComputeAndSortSubtargets")]
    [SuppressMessage("Minor Code Smell", "S101:Types should be named in PascalCase", Justification = "Patch")]
    [UsedImplicitly]
    public static class ComputeAndSortSubtargets_Patch
    {
        [UsedImplicitly]
        public static void Postfix(GameLocationCharacter caster, List<GameLocationCharacter> subTargets)
        {
            subTargets.RemoveAll(caster.CanPerceiveTarget);
        }
    }`

**Comment by PhilPJL** [comment] 2024-05-11 06:19
The reason was that as coded at the time, the  lightning arced to the nearest targets  including the caster - if I remember correctly.

**Comment by ThyWoof** [comment] 2024-05-11 15:31
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/ec2773b3-9104-452e-b2f8-afb41f55addb)
I have 2 enemies behind the wall. this is after patch.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/2caaed65-1c19-4b10-b3f6-ebfaf8ca6d66)
without patch.

I can confirm game discards allies from targeting so indeed the issue was targeting enemies behind walls.

**Comment by kdgmo** [comment] 2024-05-11 18:42
As another solution, how about strengthening the Dragonblood Sorcerer's abilities?
It's an increase per damage, not just a one attack roll
If this is the case, there will be no problem in setting the mode for Chain Lightning and specifying the targets.

**Comment by ThyWoof** [comment] 2024-05-12 22:33
Fixed with patch in DEV.

**Closed by ThyWoof** 2024-05-12 22:33 UTC
