### ISSUE TITLE
Great Weapon Master feat's bonus action attack after a kill does go away at the end of turn

### ISSUE THREAD

**Issue by BShennette** [SolastaMods/SolastaUnfinishedBusiness#5090] opened 2024-12-01 20:39 UTC
Great Weapon Master's bonus action attack on kill lasts until you use it -- at least, you can use it the next turn instead.
 
 I don't have a specific setup where this is testable, but you can use this save which has some characters with the feat in a fairly easy combat.
[Test_GFB_PlusFireDmg.zip](https://github.com/user-attachments/files/17970287/Test_GFB_PlusFireDmg.zip)

**Comment by HiddenHax** [comment] 2024-12-02 13:11
Cannot reproduce this one on my end. GWM BA attack disappeared on the same round I got it if I didn't use it.

**Comment by HiddenHax** [comment] 2024-12-02 13:12
![Screenshot_1](https://github.com/user-attachments/assets/6312b41a-9770-4ad8-8979-a22724adc804)

**Comment by ThyWoof** [comment] 2024-12-02 16:31
cannot repro. closing.

**Closed by ThyWoof** 2024-12-02 16:31 UTC
