### ISSUE TITLE
Suggestion: Marshal "Know your enemy" should not break stealth?

### ISSUE THREAD

**Issue by MartinBrandstrup** [SolastaMods/SolastaUnfinishedBusiness#2236] opened 2023-01-25 17:36 UTC
Title ^

**Comment by ThyWoof** [comment] 2023-01-25 18:12
@dolenam317

**Comment by dolenam317** [comment] 2023-01-26 01:28
Stealth already strong enough and marshall is already above the power curve. Buffing the sub is unnecessary imo.

**Comment by ThyWoof** [comment] 2023-01-26 02:39
By design. Closing.

**Closed by ThyWoof** 2023-01-26 02:39 UTC
