### ISSUE TITLE
Bug: Wildshape Issues

### ISSUE THREAD

**Issue by DStafford02** [SolastaMods/SolastaUnfinishedBusiness#4741] opened 2024-06-18 23:28 UTC
When you drop out of wildshape as a barbarian in rage, you lose your rage. 
Additionally, the stats for creatures you've wildshaped into are not included in your Combat Stats tooltips. So like if you killed something as a wildshape your kill count doesn't go up etc

**Comment by ThyWoof** [comment] 2024-06-18 23:59
Save?

**Comment by Thaladar** [comment] 2024-06-19 22:08
I was not able to reproduce this issue.  I was able to drop out of Wildshape and keep Rage.  I suspect in the OP case, losing Rage was because they took no damage and did not attack; not because of dropping Wildshape.
Round 1 - Rage, Attack
Round 2 - Wildshape (into Bear), Attack
Round 3 - Drop Wildshape, Attack (still had Rage).  

[Rage Wildshape.zip](https://github.com/user-attachments/files/15906279/Rage.Wildshape.zip)

**Comment by DStafford02** [comment] 2024-06-19 22:24
> Save?

I'm sorry, didn't know we needed to include the sav file.  I have already deleted the save (the map I was playing bugged out)

**Comment by DStafford02** [comment] 2024-06-19 22:26
> I was not able to reproduce this issue. I was able to drop out of Wildshape and keep Rage. I suspect in the OP case, losing Rage was because they took no damage and did not attack; not because of dropping Wildshape. Round 1 - Rage, Attack Round 2 - Wildshape (into Bear), Attack Round 3 - Drop Wildshape, Attack (still had Rage).
> 
> [Rage Wildshape.zip](https://github.com/user-attachments/files/15906279/Rage.Wildshape.zip)

You have misunderstood me. You are referring to what I'd call "Reverting" from wildshape, as in doing it by choice by pressing the Bonus Action. 

When I say "Dropping out" of wildshape, I mean from taking too much damage. I.E. Losing all of your wildshape hitpoints during a rage.

**Comment by ThyWoof** [comment] 2024-06-19 23:20
this is a very collateral scenario. Won't fix.

**Closed by ThyWoof** 2024-06-19 23:20 UTC
