### ISSUE TITLE
Warlock invocations 

### ISSUE THREAD

**Issue by Master999999999** [SolastaMods/SolastaUnfinishedBusiness#2410] opened 2023-02-11 12:15 UTC
Multiclassing into warlock is broken. When choosing invocations depending on sublcass I have to take 25-35 options.  Its not possible so I cant level up.

**Comment by CEDSS** [comment] 2023-02-11 12:41
This has been reported before, and apparently it was fixed on version 1.4.33.33.

The problem is that the "Latest" release right now is version 1.4.33.32, the Master version is also 1.4.33.32, and the dev version is a WIP of 1.4.33.34.

We seem to have skipped the release of version 1.4.33.33.

It'll most likely be fixed as soon as version 1.4.33.34 is released, as it includes the Warlock fix from 1.4.33.33.

**Comment by ThyWoof** [comment] 2023-02-11 17:26
to be fixed on .24. meanwhile please compile from DEV.

**Closed by ThyWoof** 2023-02-11 17:26 UTC
