### ISSUE TITLE
Respec after enabling 4 Feats at Character creation omits the 4 feats. 

### ISSUE THREAD

**Issue by Axeborne** [SolastaMods/SolastaUnfinishedBusiness#3130] opened 2023-05-05 00:57 UTC
How to report issues
The versions of Solasta and this mod.
Solasta Version 1.4.33 Public
Unfinished Business 1.4.33.82-

A list of other mods you have installed [you shouldn't have any].
Unfinished Business

A short description of the bug.
After clicking respec while having the 4 feats for character creation, it takes you through character creation again, but does not offer the 4 feats.  

I am also curious where to suggest options to be added for Unfinished Business? Please advise.

This makes the respec option much less desirable to use.

A step-by-step procedure to reproduce it.
enable 4 feats at character creation & respec a character created this way.  

The save, character and log files.
HINT: Check the folder C:\UsersYOUR_USER_NAME\AppData\LocalLow\Tactical Adventures\Solasta for the info we need.
Github is refusing the drag & drop files options for those requested (character, saves). I zipped them to allow for upload.

[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11378410/Player.log)
[Dragonborne Socrata 7.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402577/Dragonborne.Socrata.7.zip)
[Eirini.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402578/Eirini.zip)
[Ianthe.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402579/Ianthe.zip)
[Kava.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402580/Kava.zip)
[Sora.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402581/Sora.zip)
[Stasia.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402582/Stasia.zip)
[Thava.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11402583/Thava.zip)

**Comment by ThyWoof** [comment] 2023-05-05 01:26
RESPEC simply starts a new hero vanilla creation process. I’ll double check just in case.

**Comment by ThyWoof** [comment] 2023-05-05 02:01
![image](https://user-images.githubusercontent.com/13087646/236363792-dee12090-909e-4bd5-a5e5-d4114b050af2.png)
RESPEC ongoing. We add the first level feat to races. I indeed cannot reproduce.
![image](https://user-images.githubusercontent.com/13087646/236363865-43b11708-de4a-4b82-b4f1-16a8c3fc201b.png)
closing as not a bug.

**Closed by ThyWoof** 2023-05-05 02:01 UTC
